List<String> Currency = [
  " ريال سعودي",
  "درهم إماراتي",
  "ريال عماني",
  "دينار أردني",
  "جنيه مصري",
  "دينار عراقي",
  "دينار جزائري",
  "دينار بحريني",
  "دينار كويتي",
  "ليرة لبنانية",
  "ريال قطري",
  "ليرة سورية",
  "جنيه سوداني",
  "دينار تونسي",
  "ريال يمني",
  "دينار ليبي",
  "درهم مغربي",
  "الدولار الأمريكي (USD)",
  " اليورو (EUR)",
  "الين الياباني (JPY)",
  "فرنك سويسري (CHF)",
  "دولار كندي (CAD)",
];
List<String> Currency2 = [
  "lib/assets/image/1.png",
  "lib/assets/image/2.png",
  "lib/assets/image/3.png",
  "lib/assets/image/4.png",
  "lib/assets/image/5.png",
  "lib/assets/image/6.png",
  "lib/assets/image/7.png",
  "lib/assets/image/8.png",
  "lib/assets/image/9.png",
  "lib/assets/image/10.png",
  "lib/assets/image/11.png",
  "lib/assets/image/12.png",
  "lib/assets/image/13.png",
  "lib/assets/image/14.png",
  "lib/assets/image/15.png",
  "lib/assets/image/16.png",
  "lib/assets/image/17.png",
  "lib/assets/image/18.png",
  "lib/assets/image/19.png",
  "lib/assets/image/20.png",
  "lib/assets/image/21.png",
  "lib/assets/image/22.png",
];
